apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "mosquitto.name" . }}
    labels:
        app.kubernetes.io/name: {{ include "mosquitto.name" . }}
        helm.sh/chart: {{ include "mosquitto.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
    mosquitto.conf: |-
{{- if .Values.config }}
{{ .Values.config | indent 8 }}
{{- end -}}
