{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "mosquitto.name" . }}
    labels:
        app: {{ include "mosquitto.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    accessModes:
        - {{ .Values.persistence.accessMode | quote }}
    resources:
        requests:
            storage: {{ .Values.persistence.size | quote }}

{{- if .Values.persistence.storageClass }}
    storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- else }}
    storageClassName: standard
{{- end }}

{{- end }}
