apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    helm.sh/chart: {{ include "mosquitto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name | quote }}
      targetPort: {{ .port | int }}
      protocol: TCP
      port: {{ .port | int }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
