apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    helm.sh/chart: {{ include "mosquitto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port | quote }}
      targetPort: {{ .name | quote }}
      protocol: TCP
      name: {{ .name | quote }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
