# Default values for mosquitto.
replicaCount: 1

image:
  repository: eclipse-mosquitto
  tag: 1.6.7
  pullPolicy: IfNotPresent

fullnameOverride: ""
nameOverride: ""

service:
  type: "ClusterIP" #NodePort
  ports:
    - name: "mqtt"
      port: 1883
    - name: "websocket"
      port: 9001

ingress:
  enabled: false
  tls: false
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  hostname:
  secretName:

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass:

config: |-
  log_dest stdout
  port 1883
  bind_address 0.0.0.0
  listener 9001
  protocol websockets
  persistence true
  persistence_location /mosquitto/data/
